language: ruby
rvm:
- 2.3.0
script:
- bundle exec rspec
before_script:
- psql -c 'create database anacapa_grader_alpha_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
deploy:
  provider: heroku
  api_key:
    secure: drbGo+louNAfgZZ5XDb2YqD2QPGhgTrSioxki3qlgFSGwIgDXty8gtbXbVme//S1HXrR+1M4eRdEzryF6/NnRURq8LX27KaRcb8OtIWWTUL+z4rSNacPjbXyGZqvn7h+IqNbO9OeV2dKd2Kv5oJVT9ral0SsFxWKRENlNo/6IHOUU0cmwCCfEI2puDZ5r4bcYul20+FYxdD4Rox18v7klYe+2k94Nh+FFwbNdtZWcEQxtQUjC2Fr4Hru59G1RIp0Pimmhuss+F7s4YLpVCCKB2WstVeiU1dNx5/ApBjNc1w3ZOwAS0TK4pe1U8YODPJuA/x6IxcFwlGwhRYWgtSYmnpPeybhzEvGSva8DPUSfgxDzyzKGJWO/wNmqfEf3hrgn0HDm/6Gv3NB4FCJCwdyB0lwcEMb0oUMdJRy0GBa89BhxLwQNhBiX5VmTsI+dnnCVgavYd0Z646R0VLMBx/2UVJ/qJHLlVDmPEEgYhB8N2zxj2W0jYjIj7ItCAh+NezLEN6Jl2wvu7hQmnMxtSb5iEfzQc8dSeVLendeq6WC0PMP0ms1D9lBquYJ80FbDI3uht1feB41mbh81cKtyi82SkDP0dt5kCf5ZLst6A+bP/AmCzqpQfZAhRZlJAwkWYF2xIsJSupAeBkBJ8TNh5W4/24oSaFYkAqvIR1R4PS4GqA=
  app: anacapa-grader-alpha
  on:
    repo: project-anacapa/anacapa-grader-alpha
notifications:
  slack:
    secure: nwAL09FGsE3rx/0gSNVY+CNVyyzEaCMvIa3+a6bciz+JabtpvFo2PSVq3M+vFxaAFtmElKg3eXrjCy4GgFsg8E/YZrXlNeoTMZl2eohBW4gbF7wWWp5SD4bsaAhXGl76O3P/mtIkajI5fBOpIyP2/o0n7yz+GEeDHz8HU6DtDe0o7MwNTRn22s2KARTqCAVSfSfCP0SGOKC3b/0+KjVxs3/IxgOquR2fxfqZHo+uHcXBfcyqsPlPc/1KeYbAXkCd8IFFhTzQKTm727ASD0jqDtH1WcoWHclpBbEYCYQCzexwgpb0ipl9CQlqxvp/OgKL09k/H0EyQliLBopTd2lNgkg/wLOhwXS4AfRXwWefBIV7QdUUMXzKWjJjTt8cDixQR87DyKqXSByxH0QexEw7QQm4Uwuusl5wlHGVlhp5YNaE1cJsQHkS5Q1elYt7jwO5xhObHjuiZoEF0SS9jMOvsDddGTWYDavv1AukZj46Y2Ax4d9ZsQzDfXDrmW49bMqmKRyVKWVKigWyGQ9fkoANZylsh08RyxyQnaJUjbDH/wkVtS9guL2WCIf65U4CVURzIRyNahSiJ+stF9mb7A3EJuM+WtH4GK2O3WLO9Xv7kqHc55ZQqndVMgiBDlbzmkKP7r/9lgZXEtl0/a4DMG2RHc1qyD+uRuX1mY6Mp2lBwaM=
